const SITE_VERSION = '2.4';
const DATA = window.DOTA_WIKI_DATA || {heroes:[],items:[],mechanics:[],guides:[],roles:[],glossary:[],patches:[]};
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const norm = v => String(v ?? '').toLowerCase().trim();
const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const pageUrl = page => `${page}?v=${SITE_VERSION}`;
const heroUrl = slug => `hero.html?v=${SITE_VERSION}&hero=${encodeURIComponent(slug)}`;
const pills = arr => (arr||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('');
const tags = arr => (arr||[]).map(x=>`<span>${esc(x)}</span>`).join('');
const storeKey = (t)=>`dotawiki:v4:fav:${t}`;
const oldStoreKey = (t)=>`dotawiki:v3:fav:${t}`;
function getFav(t){try{const fresh=localStorage.getItem(storeKey(t)); if(fresh) return JSON.parse(fresh)||[]; const old=localStorage.getItem(oldStoreKey(t)); if(old){localStorage.setItem(storeKey(t),old);return JSON.parse(old)||[]} return []}catch{return []}}
function setFav(t,v){localStorage.setItem(storeKey(t),JSON.stringify([...new Set(v)]))}
function isFav(t,id){return getFav(t).includes(id)}
function toggleFav(t,id){const a=getFav(t);setFav(t,a.includes(id)?a.filter(x=>x!==id):[...a,id])}
function fallbackSvg(label){const safe=encodeURIComponent(String(label||'?').slice(0,2).toUpperCase());return `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 240'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' x2='1'%3E%3Cstop stop-color='%23c8322b'/%3E%3Cstop offset='1' stop-color='%23f0b35f'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='400' height='240' fill='%23101116'/%3E%3Ccircle cx='325' cy='35' r='120' fill='url(%23g)' opacity='.35'/%3E%3Ctext x='50%25' y='55%25' dominant-baseline='middle' text-anchor='middle' font-size='72' fill='%23fff' font-family='Arial' font-weight='800'%3E${safe}%3C/text%3E%3C/svg%3E`}
function setupMenu(){const b=$('[data-menu-button]'),m=$('[data-menu]');b?.addEventListener('click',()=>m?.classList.toggle('open'));document.addEventListener('click',e=>{if(!m?.classList.contains('open'))return;if(e.target.closest('.site-header'))return;m.classList.remove('open')})}
function setupTheme(){const b=$('[data-theme-toggle]');if(localStorage.getItem('dotawiki:theme')==='light')document.body.classList.add('light-theme');if(b)b.textContent=document.body.classList.contains('light-theme')?'☀':'☾';b?.addEventListener('click',()=>{document.body.classList.toggle('light-theme');const t=document.body.classList.contains('light-theme')?'light':'dark';localStorage.setItem('dotawiki:theme',t);b.textContent=t==='light'?'☀':'☾'})}
function markActiveNav(){const file=location.pathname.split('/').pop()||'index.html';$$('.main-nav a').forEach(a=>{const href=(a.getAttribute('href')||'').split('?')[0];a.classList.toggle('active',href===file || (file==='guides.html'&&href==='roles.html'))})}
function fillSelect(sel,values){const el=$(sel); if(!el || el.dataset.ready) return; el.dataset.ready='1'; el.innerHTML += [...new Set(values)].filter(Boolean).sort((a,b)=>a.localeCompare(b,'ru')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function heroCard(h){return `<article class="wiki-card hero-card"><button class="fav-button ${isFav('heroes',h.slug)?'active':''}" data-fav-type="heroes" data-fav-id="${esc(h.slug)}" aria-label="Избранное">★</button><div class="hero-img-wrap"><img src="${esc(h.image)}" alt="${esc(h.name)}" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"></div><div class="card-body"><div class="card-meta"><span>${esc(h.attribute)}</span><span>${esc(h.complexity)}</span></div><h2>${esc(h.name)}</h2><p>${esc(h.overview)}</p><div class="pill-row">${pills(h.roles)}</div><a class="card-link" href="${heroUrl(h.slug)}">Открыть героя →</a></div></article>`}
function itemCard(it){return `<article class="item-card"><button class="fav-button ${isFav('items',it.slug)?'active':''}" data-fav-type="items" data-fav-id="${esc(it.slug)}" aria-label="Избранное">★</button><img class="item-icon" src="${esc(it.image)}" alt="${esc(it.name)}" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSvg(it.name)}'"><div><div class="card-meta"><span>${esc(it.category)}</span></div><h3>${esc(it.name)}</h3><p>${esc(it.description)}</p><div class="taglist">${tags(it.tags)}</div></div></article>`}
let favRedraw=()=>{};
function setupFavButtons(redraw){if(redraw) favRedraw=redraw;if(setupFavButtons.bound) return;setupFavButtons.bound=true;document.addEventListener('click',e=>{const b=e.target.closest('[data-fav-id]');if(!b)return;e.preventDefault();toggleFav(b.dataset.favType,b.dataset.favId);favRedraw?.()})}
function setupGlobalSearch(){const form=$('[data-global-search]'), input=$('#globalSearch'), box=$('#globalResults'); if(!form||!input||!box)return; const pool=[...DATA.heroes.map(h=>({type:'Герой',title:h.name,text:[h.attribute,...(h.roles||[])].join(' · '),url:heroUrl(h.slug),search:[h.name,h.attribute,(h.roles||[]).join(' '),h.overview].join(' ')})),...DATA.items.map(i=>({type:'Предмет',title:i.name,text:i.category,url:pageUrl('items.html'),search:[i.name,i.category,i.description,(i.tags||[]).join(' ')].join(' ')})),...DATA.glossary.map(g=>({type:'Термин',title:g.term,text:g.definition,url:pageUrl('glossary.html'),search:g.term+' '+g.definition})),...DATA.mechanics.map(m=>({type:'Механика',title:m.title,text:m.text,url:pageUrl('mechanics.html'),search:m.title+' '+m.text}))]; function draw(){const q=norm(input.value); if(q.length<2){box.hidden=true;box.innerHTML='';return} const res=pool.filter(x=>norm(x.search).includes(q)).slice(0,8); box.hidden=false; box.innerHTML=res.length?res.map(x=>`<a class="global-result" href="${esc(x.url)}"><span>${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(x.text)}</small></a>`).join(''):'<div class="global-empty">Ничего не найдено</div>'} input.addEventListener('input',draw); input.addEventListener('focus',draw); form.addEventListener('submit',e=>{e.preventDefault();const first=box.querySelector('a'); if(first) location.href=first.href}); document.addEventListener('click',e=>{if(!form.contains(e.target)) box.hidden=true})}
function renderHome(){const stats=$('#siteStats');if(stats){stats.innerHTML=[['Героев в базе',DATA.heroes.length],['Карточки предметов',DATA.items.length],['Механики',DATA.mechanics.length],['Термины',DATA.glossary.length]].map(([a,b])=>`<article class="stat-card"><strong>${b}</strong><span>${a}</span></article>`).join('')} const home=$('#homeHeroes');if(home){const favs=getFav('heroes');const arr=favs.map(slug=>DATA.heroes.find(h=>h.slug===slug)).filter(Boolean);home.innerHTML=arr.length?arr.map(heroCard).join(''):`<div class="empty-state favorites-empty"><h3>Избранных героев пока нет</h3><p>Отметка звездой на карточке героя добавит его в этот блок.</p><a class="button primary" href="${pageUrl('heroes.html')}">Открыть героев</a></div>`} setupFavButtons(()=>renderHome()); const stack=$('#heroStack');if(stack){const picks=['axe','invoker','phantom_assassin'].map(s=>DATA.heroes.find(h=>h.slug===s)).filter(Boolean);stack.innerHTML=picks.map(h=>`<div class="stack-card"><img src="${esc(h.image)}" alt="${esc(h.name)}" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"><span>${esc(h.name)}</span><small>${esc(h.roles.join(' · '))}</small></div>`).join('')}}
function renderHeroes(){const list=$('#heroesList');if(!list)return;fillSelect('#attributeFilter',DATA.heroes.map(h=>h.attribute));fillSelect('#roleFilter',DATA.heroes.flatMap(h=>h.roles));fillSelect('#complexityFilter',DATA.heroes.map(h=>h.complexity));let favOnly=false;const redraw=()=>{const q=norm($('#heroSearch')?.value),attr=$('#attributeFilter')?.value,role=$('#roleFilter')?.value,cx=$('#complexityFilter')?.value;let arr=DATA.heroes.filter(h=>(!q||norm([h.name,h.attribute,h.complexity,h.roles.join(' '),h.overview].join(' ')).includes(q))&&(!attr||h.attribute===attr)&&(!role||h.roles.includes(role))&&(!cx||h.complexity===cx)&&(!favOnly||isFav('heroes',h.slug)));$('#heroesCount').textContent=`Показано героев: ${arr.length} из ${DATA.heroes.length}`;list.innerHTML=arr.length?arr.map(heroCard).join(''):'<div class="empty-state">Ничего не найдено. Измените параметры поиска.</div>'};['#heroSearch','#attributeFilter','#roleFilter','#complexityFilter'].forEach(s=>$(s)?.addEventListener('input',redraw));$('#onlyFavHeroes')?.addEventListener('click',e=>{favOnly=!favOnly;e.currentTarget.classList.toggle('active',favOnly);redraw()});setupFavButtons(redraw);redraw()}
function abilityGrid(abilities){return abilities?.length?`<div class="ability-grid">${abilities.map((a,i)=>{const name=typeof a==='string'?a:a.name;const text=typeof a==='string'?'':a.text;return `<article class="ability-card"><div class="ability-icon">${esc(String(i+1))}</div><div><h3>${esc(name)}</h3>${text?`<p>${esc(text)}</p>`:''}</div></article>`}).join('')}</div>`:'<p>Для героя пока указана общая карточка без списка способностей.</p>'}
function renderHeroDetail(){const box=$('#heroDetail');if(!box)return;const slug=new URLSearchParams(location.search).get('hero')||'';const h=DATA.heroes.find(x=>x.slug===slug)||DATA.heroes[0];document.title=`${h.name} — DotaWiki`;const mainRole=h.roles?.[0]||'Герой';box.innerHTML=`<section class="detail-hero" style="--hero-accent:${esc(h.accent||'#c8322b')}"><div><p class="eyebrow">${esc(h.attribute)} · ${esc(h.complexity)}</p><h1>${esc(h.name)}</h1><p>${esc(h.overview)}</p><div class="mini-stats"><span>Основная роль: ${esc(mainRole)}</span><span>${esc(h.laneName||'Гибкая позиция')}</span></div><div class="pill-row">${pills(h.roles)}</div><div class="hero-actions"><button class="button primary" data-fav-type="heroes" data-fav-id="${esc(h.slug)}">★ ${isFav('heroes',h.slug)?'В избранном':'В избранное'}</button><a class="button ghost" href="${pageUrl('heroes.html')}">Все герои</a></div></div><div class="detail-hero-art"><img src="${esc(h.portrait||h.image)}" alt="${esc(h.name)}" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"></div></section><section class="detail-grid"><article class="wiki-panel"><h2>Описание</h2><p>${esc(h.description)}</p></article><article class="wiki-panel"><h2>Сильные стороны</h2><ul>${(h.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="wiki-panel"><h2>Слабые стороны</h2><ul>${(h.weaknesses||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="wiki-panel"><h2>Типовые предметы</h2><div class="item-chips">${tags(h.bestItems)}</div></article><article class="wiki-panel wide-card"><h2>Способности</h2>${abilityGrid(h.abilities)}</article><article class="wiki-panel"><h2>Противодействие</h2><div class="item-chips">${tags(h.counters)}</div></article><article class="wiki-panel"><h2>Сочетания</h2><div class="item-chips">${tags(h.synergy)}</div></article></section>`;setupFavButtons(()=>renderHeroDetail())}
function renderItems(){const list=$('#itemsList');if(!list)return;fillSelect('#itemCategory',DATA.items.map(i=>i.category));let favOnly=false;const redraw=()=>{const q=norm($('#itemSearch')?.value),cat=$('#itemCategory')?.value;let arr=DATA.items.filter(i=>(!q||norm([i.name,i.category,i.description,(i.tags||[]).join(' ')].join(' ')).includes(q))&&(!cat||i.category===cat)&&(!favOnly||isFav('items',i.slug)));$('#itemsCount').textContent=`Показано предметов: ${arr.length} из ${DATA.items.length}`;list.innerHTML=arr.length?arr.map(itemCard).join(''):'<div class="empty-state">Ничего не найдено. Измените параметры поиска.</div>'};['#itemSearch','#itemCategory'].forEach(s=>$(s)?.addEventListener('input',redraw));$('#onlyFavItems')?.addEventListener('click',e=>{favOnly=!favOnly;e.currentTarget.classList.toggle('active',favOnly);redraw()});setupFavButtons(redraw);redraw()}
function renderMechanics(){const box=$('#mechanicsList');if(box)box.innerHTML=DATA.mechanics.map(m=>`<article class="article-card"><div class="mechanic-icon">${esc(m.icon)}</div><h2>${esc(m.title)}</h2><p>${esc(m.text)}</p></article>`).join('')}
function renderGuides(){const box=$('#guidesList');if(box)box.innerHTML=(DATA.roles||DATA.guides||[]).map(g=>`<article class="article-card guide-card"><span class="level-badge">${esc(g.level)}</span><h2>${esc(g.title)}</h2><p>${esc(g.text)}</p></article>`).join('')}
const buildData={carry:{title:'Керри',cols:[['Старт','Quelling Blade','Magic Wand','Power Treads'],['Середина','Battle Fury / Maelstrom','Black King Bar','Manta Style'],['Поздняя стадия','Butterfly','Satanic','Abyssal Blade']]},mid:{title:'Мидер',cols:[['Старт','Bottle','Magic Wand','Power Treads'],['Середина','Blink / Shadow Blade','Black King Bar','Kaya item'],['Поздняя стадия','Scythe of Vyse','Refresher Orb','Aghanim’s Scepter']]},offlane:{title:'Оффлейн',cols:[['Старт','Bracer','Phase Boots','Vanguard / Hood'],['Середина','Blink Dagger','Pipe / Crimson','Black King Bar'],['Поздняя стадия','Shiva’s Guard','Lotus Orb','Refresher Orb']]},support:{title:'Саппорт',cols:[['Старт','Observer Ward','Sentry Ward','Magic Wand'],['Середина','Arcane Boots','Force Staff','Glimmer Cape'],['Поздняя стадия','Aghanim’s Shard','Lotus Orb','Scythe of Vyse']]}};
function renderBuilds(type='carry'){const box=$('#buildDetail');if(!box)return;const b=buildData[type];$$('[data-build]').forEach(x=>x.classList.toggle('active',x.dataset.build===type));box.innerHTML=`<h2>${esc(b.title)}</h2><p>Типовая структура предметов по стадиям матча.</p><div class="build-columns">${b.cols.map(col=>`<div class="build-col"><h3>${esc(col[0])}</h3><ul>${col.slice(1).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`).join('')}</div>`}
function setupBuilds(){if(!$('#buildDetail'))return;$$('[data-build]').forEach(b=>b.addEventListener('click',()=>renderBuilds(b.dataset.build)));renderBuilds('carry')}
function renderGlossary(){const box=$('#glossaryList');if(!box)return;const redraw=()=>{const q=norm($('#glossarySearch')?.value);const arr=DATA.glossary.filter(g=>!q||norm(g.term+' '+g.definition).includes(q));box.innerHTML=arr.map(g=>`<article class="glossary-item"><h2>${esc(g.term)}</h2><p>${esc(g.definition)}</p></article>`).join('')||'<div class="empty-state">Термин не найден.</div>'};$('#glossarySearch')?.addEventListener('input',redraw);redraw()}
function renderPatches(){const box=$('#patchTimeline');if(!box)return;box.innerHTML=DATA.patches.slice(0,2).map(p=>`<article class="timeline-item"><div class="timeline-version">${esc(p.version)}</div><div class="timeline-content"><p class="eyebrow">${esc(p.date)}</p><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p>${p.highlights?.length?`<ul class="patch-highlights">${p.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${p.url?`<a class="button small ghost patch-link" href="${esc(p.url)}" target="_blank" rel="noopener">Открыть официальный патчноут →</a>`:''}</div></article>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{setupMenu();setupTheme();markActiveNav();setupGlobalSearch();renderHome();renderHeroes();renderHeroDetail();renderItems();renderMechanics();renderGuides();setupBuilds();renderGlossary();renderPatches();});
