
const SITE_VERSION = '2.5';
const DATA = window.DOTA_WIKI_DATA || {heroes:[],items:[],mechanics:[],guides:[],roles:[],glossary:[],patches:[]};
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const params = new URLSearchParams(location.search);
const norm = v => String(v ?? '').toLowerCase().trim();
const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function pageUrl(page, extra={}){const p=new URLSearchParams({v:SITE_VERSION});Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&String(v)!=='')p.set(k,v)});return `${page}?${p.toString()}`}
const heroUrl = slug => pageUrl('hero.html',{hero:slug});
const itemUrl = slug => pageUrl('item.html',{item:slug});
const pills = arr => (arr||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('');
const tags = arr => (arr||[]).map(x=>`<span>${esc(x)}</span>`).join('');
const storeKey = t => `dotawiki:v5:${t}`;
const oldKeys = t => [`dotawiki:v4:fav:${t}`,`dotawiki:v3:fav:${t}`];
function readStore(key, fallback=[]){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function writeStore(key, value){try{localStorage.setItem(key, JSON.stringify(value))}catch{}}
function getFav(t){const cur=readStore(storeKey(`fav:${t}`),null); if(cur) return cur; for(const k of oldKeys(t)){const old=readStore(k,null); if(old){writeStore(storeKey(`fav:${t}`),old); return old}} return []}
function setFav(t,v){writeStore(storeKey(`fav:${t}`),[...new Set(v)])}
function isFav(t,id){return getFav(t).includes(id)}
function toggleFav(t,id){const a=getFav(t);setFav(t,a.includes(id)?a.filter(x=>x!==id):[...a,id])}
function fallbackSvg(label){const safe=encodeURIComponent(String(label||'?').slice(0,2).toUpperCase());return `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 240'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' x2='1'%3E%3Cstop stop-color='%23c8322b'/%3E%3Cstop offset='1' stop-color='%23f0b35f'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='400' height='240' fill='%23101116'/%3E%3Ccircle cx='325' cy='35' r='120' fill='url(%23g)' opacity='.35'/%3E%3Ctext x='50%25' y='55%25' dominant-baseline='middle' text-anchor='middle' font-size='72' fill='%23fff' font-family='Arial' font-weight='800'%3E${safe}%3C/text%3E%3C/svg%3E`}
function setupMenu(){const b=$('[data-menu-button]'),m=$('[data-menu]');b?.addEventListener('click',()=>m?.classList.toggle('open'));document.addEventListener('click',e=>{if(!m?.classList.contains('open'))return;if(e.target.closest('.site-header'))return;m.classList.remove('open')})}
function setupTheme(){const b=$('[data-theme-toggle]');if(localStorage.getItem('dotawiki:theme')==='light')document.body.classList.add('light-theme');if(b)b.textContent=document.body.classList.contains('light-theme')?'☀':'☾';b?.addEventListener('click',()=>{document.body.classList.toggle('light-theme');const light=document.body.classList.contains('light-theme');localStorage.setItem('dotawiki:theme',light?'light':'dark');b.textContent=light?'☀':'☾'})}
function markActiveNav(){const file=(location.pathname.split('/').pop()||'index.html').replace('guides.html','roles.html');$$('.main-nav a').forEach(a=>{const href=(a.getAttribute('href')||'').split('?')[0];a.classList.toggle('active',href===file||(file===''&&href==='index.html'))})}
function fillSelect(sel, values){const el=$(sel); if(!el)return; [...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ru')).forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`))}
function setupFavButtons(after){$$('[data-fav-type]').forEach(btn=>{btn.onclick=(e)=>{e.preventDefault();e.stopPropagation();const t=btn.dataset.favType,id=btn.dataset.favId;toggleFav(t,id);if(after)after();else{btn.classList.toggle('active',isFav(t,id));btn.textContent=btn.classList.contains('active')?'★':'★'}}})}
function heroCard(h, compact=false){return `<article class="wiki-card hero-card ${compact?'compact-card':''}"><button class="fav-button ${isFav('heroes',h.slug)?'active':''}" data-fav-type="heroes" data-fav-id="${esc(h.slug)}" aria-label="Избранное">★</button><a class="hero-img-wrap" href="${heroUrl(h.slug)}"><img src="${esc(h.image)}" alt="${esc(h.name)}" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"></a><div class="card-body"><div class="card-meta"><span>${esc(h.attribute)}</span><span>${esc(h.complexity)}</span></div><h2><a href="${heroUrl(h.slug)}">${esc(h.name)}</a></h2><p>${esc(h.overview)}</p><div class="pill-row">${pills(h.roles)}</div><a class="card-link" href="${heroUrl(h.slug)}">Открыть героя →</a></div></article>`}
function itemCard(it){return `<article class="item-card"><button class="fav-button ${isFav('items',it.slug)?'active':''}" data-fav-type="items" data-fav-id="${esc(it.slug)}" aria-label="Избранное">★</button><a href="${itemUrl(it.slug)}"><img class="item-icon" src="${esc(it.image)}" alt="${esc(it.name)}" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSvg(it.name)}'"></a><div><div class="card-meta"><span>${esc(it.category)}</span></div><h3><a href="${itemUrl(it.slug)}">${esc(it.name)}</a></h3><p>${esc(it.description)}</p><div class="taglist">${tags(it.tags)}</div><a class="card-link mini-link" href="${itemUrl(it.slug)}">Подробнее →</a></div></article>`}
function setupGlobalSearch(){const form=$('[data-global-search]'), input=$('#globalSearch'), box=$('#globalResults'); if(!form||!input||!box)return; const pool=[...DATA.heroes.map(h=>({type:'Герой',title:h.name,text:[h.attribute,...(h.roles||[])].join(' · '),url:heroUrl(h.slug),search:[h.name,h.attribute,(h.roles||[]).join(' '),h.overview].join(' ')})),...DATA.items.map(i=>({type:'Предмет',title:i.name,text:i.category,url:itemUrl(i.slug),search:[i.name,i.category,i.description,(i.tags||[]).join(' ')].join(' ')})),...DATA.glossary.map(g=>({type:'Термин',title:g.term,text:g.definition,url:pageUrl('glossary.html',{q:g.term}),search:g.term+' '+g.definition})),...DATA.mechanics.map(m=>({type:'Механика',title:m.title,text:m.text,url:pageUrl('mechanics.html',{q:m.title}),search:m.title+' '+m.text}))]; function draw(){const q=norm(input.value); if(q.length<2){box.hidden=true;box.innerHTML='';return} const res=pool.filter(x=>norm(x.search).includes(q)).slice(0,9); box.hidden=false; box.innerHTML=res.length?res.map(x=>`<a class="global-result" href="${esc(x.url)}"><span>${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(x.text)}</small></a>`).join(''):'<div class="global-empty">Ничего не найдено</div>'} input.addEventListener('input',draw); input.addEventListener('focus',draw); form.addEventListener('submit',e=>{e.preventDefault();const first=box.querySelector('a'); if(first) location.href=first.href}); document.addEventListener('click',e=>{if(!form.contains(e.target)) box.hidden=true})}
function getHero(slug){return DATA.heroes.find(h=>h.slug===slug)}
function getItem(slug){return DATA.items.find(i=>i.slug===slug)}
function rememberHero(slug){if(!slug)return;const key=storeKey('recent:heroes');const arr=readStore(key,[]).filter(x=>x!==slug);arr.unshift(slug);writeStore(key,arr.slice(0,6))}
function renderHome(){const stats=$('#siteStats');if(stats){stats.innerHTML=[['Героев в базе',DATA.heroes.length],['Карточки предметов',DATA.items.length],['Механики',DATA.mechanics.length],['Термины',DATA.glossary.length]].map(([a,b])=>`<article class="stat-card"><strong>${b}</strong><span>${a}</span></article>`).join('')} const stack=$('#heroStack');if(stack){const picks=['axe','invoker','phantom_assassin'].map(getHero).filter(Boolean);stack.innerHTML=picks.map(h=>`<div class="stack-card"><img src="${esc(h.image)}" alt="${esc(h.name)}" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"><span>${esc(h.name)}</span><small>${esc(h.roles.join(' · '))}</small></div>`).join('')} const popular=$('#popularHeroes');if(popular){const picks=['axe','juggernaut','invoker','phantom_assassin','pudge','crystal_maiden'].map(getHero).filter(Boolean);popular.innerHTML=picks.map(h=>heroCard(h,true)).join('')} const patchBox=$('#homePatches');if(patchBox){patchBox.innerHTML=DATA.patches.slice(0,2).map(p=>`<article class="article-card patch-mini"><span class="level-badge">${esc(p.version)}</span><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p><a class="card-link" href="${pageUrl('patches.html')}">К патчам →</a></article>`).join('')} const favs=getFav('heroes');const count=$('#favoriteHeroCount'); if(count)count.textContent=favs.length; const clear=$('#clearFavHeroes'); if(clear){clear.hidden=favs.length===0; clear.onclick=()=>{setFav('heroes',[]);renderHome()}} const home=$('#homeHeroes');if(home){const arr=favs.map(getHero).filter(Boolean);home.innerHTML=arr.length?arr.map(h=>heroCard(h,true)).join(''):`<div class="empty-state favorites-empty"><h3>Избранных героев пока нет</h3><p>Отметка звездой на карточке героя добавит его в этот блок.</p><a class="button primary" href="${pageUrl('heroes.html')}">Открыть героев</a></div>`} const recent=$('#recentHeroes');if(recent){const arr=readStore(storeKey('recent:heroes'),[]).map(getHero).filter(Boolean);recent.innerHTML=arr.length?arr.map(h=>heroCard(h,true)).join(''):`<div class="empty-state">Открытые герои появятся здесь.</div>`} setupFavButtons(()=>renderHome())}
function renderHeroes(){const list=$('#heroesList');if(!list)return;fillSelect('#attributeFilter',DATA.heroes.map(h=>h.attribute));fillSelect('#roleFilter',DATA.heroes.flatMap(h=>h.roles));fillSelect('#complexityFilter',DATA.heroes.map(h=>h.complexity));const search=$('#heroSearch'); if(params.get('q')&&search) search.value=params.get('q');let favOnly=false;const redraw=()=>{const q=norm(search?.value),attr=$('#attributeFilter')?.value,role=$('#roleFilter')?.value,cx=$('#complexityFilter')?.value;let arr=DATA.heroes.filter(h=>(!q||norm([h.name,h.attribute,h.complexity,h.roles.join(' '),h.overview,h.description].join(' ')).includes(q))&&(!attr||h.attribute===attr)&&(!role||h.roles.includes(role))&&(!cx||h.complexity===cx)&&(!favOnly||isFav('heroes',h.slug)));$('#heroesCount').textContent=`Показано героев: ${arr.length} из ${DATA.heroes.length}`;list.innerHTML=arr.length?arr.map(heroCard).join(''):'<div class="empty-state">Ничего не найдено. Измените параметры поиска.</div>';setupFavButtons(redraw)};['#heroSearch','#attributeFilter','#roleFilter','#complexityFilter'].forEach(s=>$(s)?.addEventListener('input',redraw));$('#onlyFavHeroes')?.addEventListener('click',e=>{favOnly=!favOnly;e.currentTarget.classList.toggle('active',favOnly);redraw()});redraw()}
function abilityGrid(abilities){return abilities?.length?`<div class="ability-grid">${abilities.map((a,i)=>{const name=typeof a==='string'?a:a.name;const text=typeof a==='string'?'':a.text;return `<article class="ability-card"><div class="ability-icon">${esc(String(i+1))}</div><div><h3>${esc(name)}</h3>${text?`<p>${esc(text)}</p>`:''}</div></article>`}).join('')}</div>`:'<p>Список способностей появится после обновления базы.</p>'}
function itemLinkList(names){const arr=(names||[]).map(n=>DATA.items.find(i=>i.name===n)).filter(Boolean);return arr.length?arr.map(i=>`<a class="chip-link" href="${itemUrl(i.slug)}">${esc(i.name)}</a>`).join(''):(names||[]).map(n=>`<span>${esc(n)}</span>`).join('')}
function glossaryLinks(names){return (names||[]).map(n=>`<a class="chip-link" href="${pageUrl('glossary.html',{q:n})}">${esc(n)}</a>`).join('')}
function renderHeroDetail(){const box=$('#heroDetail');if(!box)return;const slug=params.get('hero')||'';const h=getHero(slug)||DATA.heroes[0];rememberHero(h.slug);document.title=`${h.name} — DotaWiki`;const mainRole=h.roles?.[0]||'Герой';box.innerHTML=`<section class="detail-hero" style="--hero-accent:${esc(h.accent||'#c8322b')}"><div><p class="eyebrow">${esc(h.attribute)} · ${esc(h.complexity)}</p><h1>${esc(h.name)}</h1><p>${esc(h.overview)}</p><div class="mini-stats"><span>Основная роль: ${esc(mainRole)}</span><a href="${pageUrl('roles.html',{q:mainRole})}">${esc(h.laneName||'Гибкая позиция')}</a></div><div class="pill-row">${pills(h.roles)}</div><div class="hero-actions"><button class="button primary" data-fav-type="heroes" data-fav-id="${esc(h.slug)}">★ ${isFav('heroes',h.slug)?'В избранном':'В избранное'}</button><a class="button ghost" href="${pageUrl('compare.html',{a:h.slug})}">Сравнить</a><a class="button ghost" href="${pageUrl('heroes.html')}">Все герои</a></div></div><div class="detail-hero-art"><img src="${esc(h.portrait||h.image)}" alt="${esc(h.name)}" onerror="this.onerror=null;this.src='${fallbackSvg(h.name)}'"></div></section><section class="detail-grid"><article class="wiki-panel"><h2>Описание</h2><p>${esc(h.description)}</p></article><article class="wiki-panel"><h2>Сильные стороны</h2><ul>${(h.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="wiki-panel"><h2>Слабые стороны</h2><ul>${(h.weaknesses||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="wiki-panel"><h2>Типовые предметы</h2><div class="item-chips">${itemLinkList(h.bestItems)}</div></article><article class="wiki-panel wide-card"><h2>Способности</h2>${abilityGrid(h.abilities)}</article><article class="wiki-panel"><h2>Контрмеры</h2><div class="item-chips">${tags(h.counters)}</div></article><article class="wiki-panel"><h2>Связанные термины</h2><div class="item-chips">${glossaryLinks(h.relatedTerms)}</div></article></section>`;setupFavButtons(()=>renderHeroDetail())}
function renderItems(){const list=$('#itemsList');if(!list)return;fillSelect('#itemCategory',DATA.items.map(i=>i.category));const search=$('#itemSearch'); if(params.get('q')&&search) search.value=params.get('q'); if(params.get('category')&&$('#itemCategory')) $('#itemCategory').value=params.get('category');let favOnly=false;const redraw=()=>{const q=norm(search?.value),cat=$('#itemCategory')?.value;let arr=DATA.items.filter(i=>(!q||norm([i.name,i.category,i.description,(i.tags||[]).join(' ')].join(' ')).includes(q))&&(!cat||i.category===cat)&&(!favOnly||isFav('items',i.slug)));$('#itemsCount').textContent=`Показано предметов: ${arr.length} из ${DATA.items.length}`;list.innerHTML=arr.length?arr.map(itemCard).join(''):'<div class="empty-state">Ничего не найдено. Измените параметры поиска.</div>';setupFavButtons(redraw)};['#itemSearch','#itemCategory'].forEach(s=>$(s)?.addEventListener('input',redraw));$('#onlyFavItems')?.addEventListener('click',e=>{favOnly=!favOnly;e.currentTarget.classList.toggle('active',favOnly);redraw()});redraw()}
function renderItemDetail(){const box=$('#itemDetail');if(!box)return;const it=getItem(params.get('item'))||DATA.items[0];document.title=`${it.name} — DotaWiki`;box.innerHTML=`<section class="item-detail"><div class="item-detail-icon"><img src="${esc(it.image)}" alt="${esc(it.name)}" onerror="this.onerror=null;this.src='${fallbackSvg(it.name)}'"></div><div><p class="eyebrow">${esc(it.category)}</p><h1>${esc(it.name)}</h1><p>${esc(it.description)}</p><div class="taglist large-tags">${tags(it.tags)}</div><div class="hero-actions"><button class="button primary" data-fav-type="items" data-fav-id="${esc(it.slug)}">★ ${isFav('items',it.slug)?'В избранном':'В избранное'}</button><a class="button ghost" href="${pageUrl('items.html',{category:it.category})}">Категория</a></div></div></section><section class="detail-grid"><article class="wiki-panel"><h2>Назначение</h2><p>Предмет относится к категории «${esc(it.category)}» и используется по таймингам, когда команде нужны ${esc((it.tags||[]).join(', ')||'дополнительные возможности')}.</p></article><article class="wiki-panel"><h2>Полезен против</h2><div class="item-chips">${tags(it.useAgainst)}</div></article><article class="wiki-panel"><h2>Герои, которым подходит</h2><div class="item-chips">${(it.usedBy||[]).length?(it.usedBy||[]).map(h=>`<a class="chip-link" href="${heroUrl(h.slug)}">${esc(h.name)}</a>`).join(''):'<span>Зависит от роли и ситуации</span>'}</div></article><article class="wiki-panel"><h2>Похожие предметы</h2><div class="item-chips">${itemLinkList(it.relatedItems)}</div></article></section>`;setupFavButtons(()=>renderItemDetail())}
function renderMechanics(){const box=$('#mechanicsList');if(!box)return;const q=norm(params.get('q')||'');const arr=DATA.mechanics.filter(m=>!q||norm(m.title+' '+m.text).includes(q));box.innerHTML=arr.map(m=>`<article class="article-card"><div class="mechanic-icon">${esc(m.icon)}</div><h2>${esc(m.title)}</h2><p>${esc(m.text)}</p><a class="card-link" href="${pageUrl('glossary.html',{q:m.title})}">Связанные термины →</a></article>`).join('')||'<div class="empty-state">Механика не найдена.</div>'}
function renderGuides(){const box=$('#guidesList');if(!box)return;const q=norm(params.get('q')||'');const arr=(DATA.roles||DATA.guides||[]).filter(g=>!q||norm(g.title+' '+g.text+' '+g.level).includes(q));box.innerHTML=arr.map(g=>`<article class="article-card guide-card"><span class="level-badge">${esc(g.level)}</span><h2>${esc(g.title)}</h2><p>${esc(g.text)}</p><a class="card-link" href="${pageUrl('heroes.html',{q:g.title})}">Герои роли →</a></article>`).join('')||'<div class="empty-state">Раздел не найден.</div>'}
const buildData={carry:{title:'Керри',cols:[['Старт','Quelling Blade','Magic Wand','Power Treads'],['Середина','Battle Fury / Maelstrom','Black King Bar','Manta Style'],['Поздняя стадия','Butterfly','Satanic','Abyssal Blade']]},mid:{title:'Мидер',cols:[['Старт','Bottle','Magic Wand','Power Treads'],['Середина','Blink / Shadow Blade','Black King Bar','Kaya item'],['Поздняя стадия','Scythe of Vyse','Refresher Orb','Aghanim’s Scepter']]},offlane:{title:'Оффлейн',cols:[['Старт','Bracer','Phase Boots','Vanguard / Hood'],['Середина','Blink Dagger','Pipe / Crimson','Black King Bar'],['Поздняя стадия','Shiva’s Guard','Lotus Orb','Refresher Orb']]},support:{title:'Саппорт',cols:[['Старт','Observer Ward','Sentry Ward','Magic Wand'],['Середина','Arcane Boots','Force Staff','Glimmer Cape'],['Поздняя стадия','Aghanim’s Shard','Lotus Orb','Scythe of Vyse']]}};
function renderBuilds(type='carry'){const box=$('#buildDetail');if(!box)return;const b=buildData[type];$$('[data-build]').forEach(x=>x.classList.toggle('active',x.dataset.build===type));box.innerHTML=`<h2>${esc(b.title)}</h2><p>Типовая структура предметов по стадиям матча.</p><div class="build-columns">${b.cols.map(col=>`<div class="build-col"><h3>${esc(col[0])}</h3><ul>${col.slice(1).map(x=>`<li><a href="${pageUrl('items.html',{q:x.split(' / ')[0]})}">${esc(x)}</a></li>`).join('')}</ul></div>`).join('')}</div>`}
function setupBuilds(){if(!$('#buildDetail'))return;$$('[data-build]').forEach(b=>b.addEventListener('click',()=>renderBuilds(b.dataset.build)));renderBuilds('carry')}
function renderGlossary(){const box=$('#glossaryList');if(!box)return;const input=$('#glossarySearch');if(params.get('q')&&input)input.value=params.get('q');const redraw=()=>{const q=norm(input?.value);const arr=DATA.glossary.filter(g=>!q||norm(g.term+' '+g.definition).includes(q));box.innerHTML=arr.map(g=>`<article class="glossary-item"><h2>${esc(g.term)}</h2><p>${esc(g.definition)}</p><a class="card-link" href="${pageUrl('mechanics.html',{q:g.term})}">Механики →</a></article>`).join('')||'<div class="empty-state">Термин не найден.</div>'};input?.addEventListener('input',redraw);redraw()}
function renderPatches(){const summary=$('#patchSummary');if(summary){summary.innerHTML=DATA.patches.slice(0,2).map(p=>`<article class="article-card"><span class="level-badge">${esc(p.version)}</span><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p><div class="item-chips">${tags(p.sections)}</div></article>`).join('')} const box=$('#patchTimeline');if(!box)return;box.innerHTML=DATA.patches.slice(0,2).map(p=>`<article class="timeline-item"><div class="timeline-version">${esc(p.version)}</div><div class="timeline-content"><p class="eyebrow">${esc(p.date)}</p><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p>${p.highlights?.length?`<ul class="patch-highlights">${p.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${p.url?`<a class="button small ghost patch-link" href="${esc(p.url)}" target="_blank" rel="noopener">Открыть официальный патчноут →</a>`:''}</div></article>`).join('')}
function setupCompare(){const a=$('#compareA'),b=$('#compareB'),box=$('#compareResult');if(!a||!b||!box)return;const options=DATA.heroes.map(h=>`<option value="${esc(h.slug)}">${esc(h.name)}</option>`).join('');a.innerHTML=options;b.innerHTML=options;a.value=params.get('a')||'axe';b.value=params.get('b')||'pudge';if(a.value===b.value)b.value=DATA.heroes.find(h=>h.slug!==a.value)?.slug||b.value;function cellList(arr){return `<ul>${(arr||[]).slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}function redraw(){const h1=getHero(a.value)||DATA.heroes[0],h2=getHero(b.value)||DATA.heroes[1];const rows=[['Атрибут',h1.attribute,h2.attribute],['Сложность',h1.complexity,h2.complexity],['Роли',h1.roles.join(', '),h2.roles.join(', ')],['Линия',h1.laneName||'Гибкая',h2.laneName||'Гибкая'],['Сильные стороны',cellList(h1.strengths),cellList(h2.strengths)],['Слабые стороны',cellList(h1.weaknesses),cellList(h2.weaknesses)],['Типовые предметы',itemLinkList(h1.bestItems),itemLinkList(h2.bestItems)]];box.innerHTML=`<div class="compare-head"><article>${heroCard(h1,true)}</article><article>${heroCard(h2,true)}</article></div><div class="compare-table"><table><thead><tr><th>Параметр</th><th>${esc(h1.name)}</th><th>${esc(h2.name)}</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r[0])}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`;history.replaceState(null,'',pageUrl('compare.html',{a:h1.slug,b:h2.slug}));setupFavButtons(redraw)}a.addEventListener('change',redraw);b.addEventListener('change',redraw);redraw()}
document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add('js-ready');setupMenu();setupTheme();markActiveNav();setupGlobalSearch();renderHome();renderHeroes();renderHeroDetail();renderItems();renderItemDetail();renderMechanics();renderGuides();setupBuilds();renderGlossary();renderPatches();setupCompare();});
